import { and, eq, gt, lt } from "drizzle-orm";
import { db } from "./index";
import { previews, type Preview } from "./schema";

/**
 * Itineraries generated by people who have not signed in.
 *
 * A preview is not a trip. It has no owner, it expires, and the only thing
 * that can reach it is its own id. Claiming one turns it into a real trip and
 * destroys the preview, so the same itinerary is never both.
 */

/** Long enough to sign in and come back, short enough to be litter. */
const LIFETIME_MS = 24 * 60 * 60 * 1000;

/**
 * How often creating a preview also takes the bins out.
 *
 * Expiring a row is not the same as deleting it, and a table full of
 * technically-expired previews is still a table full of strangers' itineraries.
 * Sweeping on somebody else's request costs one occasional DELETE and needs no
 * scheduler, which matters because there is not one yet.
 */
const SWEEP_ODDS = 0.05;

export async function createPreview(input: {
  destination: string;
  dayCount: number;
}): Promise<Preview> {
  const [preview] = await db()
    .insert(previews)
    .values({
      /*
       * A full UUID, not the short prefixed id the rest of the app uses.
       *
       * Those are fine for trips, where the id appears in the owner's own URL
       * and the owner is checked anyway. This id is the entire credential: it
       * is the only thing that proves the holder is the person who generated
       * this, so it has to be worth guessing at.
       */
      id: crypto.randomUUID(),
      destination: input.destination,
      dayCount: input.dayCount,
      expiresAt: new Date(Date.now() + LIFETIME_MS),
    })
    .returning();

  if (Math.random() < SWEEP_ODDS) {
    // Never awaited, never allowed to fail the request that triggered it. The
    // person creating this preview did not ask to do the housekeeping.
    deleteExpiredPreviews().catch(() => null);
  }

  return preview;
}

export async function savePreviewItinerary(input: {
  previewId: string;
  rawItinerary: string;
}): Promise<void> {
  await db()
    .update(previews)
    .set({ rawItinerary: input.rawItinerary })
    .where(eq(previews.id, input.previewId));
}

/**
 * A preview, if it exists and has not expired.
 *
 * Expiry is in the WHERE clause rather than checked after loading, for the
 * same reason ownership is on every trip query: a check the caller has to
 * remember is a check that eventually gets forgotten.
 */
export async function getLivePreview(previewId: string): Promise<Preview | null> {
  const [preview] = await db()
    .select()
    .from(previews)
    .where(and(eq(previews.id, previewId), gt(previews.expiresAt, new Date())))
    .limit(1);

  return preview ?? null;
}

export async function deletePreview(previewId: string): Promise<void> {
  await db().delete(previews).where(eq(previews.id, previewId));
}

/** Housekeeping, for the nightly sweep. Returns how many were removed. */
export async function deleteExpiredPreviews(): Promise<number> {
  const removed = await db()
    .delete(previews)
    .where(lt(previews.expiresAt, new Date()))
    .returning({ id: previews.id });

  return removed.length;
}
